apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-graalvm-app
  name: java-graalvm-app
  namespace: ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-graalvm-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: java-graalvm-app
    spec:
      containers:
      - name: java-graalvm-app
        image: ivaylopp/mdp-classwork-1:latest
