apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: ns1
spec:
  selector:
    matchLabels:
      app: python-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      containers:
        - name: python-app
          image: ivaylopp/mdp-classwork-1:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
              memory: 400Mi
