name: CI

on:
  push:
    branches: [ "main" ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-alpine
          push: true
          tags: ${{ github.actor }}/app:1.0-${{ github.sha }}


  flake8:
    needs: build-and-push
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install flake8
        run: sudo apt-get update && sudo apt-get install flake8

      - name: Run flake8
      # W191: indentation contains tabs
        run: flake8 --max-line-length=120 --ignore=W191 ./src/app.py


  editorconfig-checker:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Load editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run editorconfig-checker
        run: editorconfig-checker

  
  markdownlint:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run markdownlint
        uses: articulate/actions-markdownlint@v1


  trivy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.actor }}/app:1.0-${{ github.sha }}
          format: table
          exit-code: 1
          severity: CRITICAL
