name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ivaylopp/mdp-classwork-ci/.github/workflows/ci.yml@python-1.0.0
    permissions:
      packages: write
    secrets: inherit
