name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_IMAGE_TAG: ${{ github.actor }}/app:1.0-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ vars.DOCKER_IMAGE_TAG }} -f Dockerfile-alpine .

      - name: Push the Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ vars.DOCKER_IMAGE_TAG }}


  flake8:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install flake8
        run: sudo apt-get update && sudo apt-get install flake8

      - name: Run flake8
      # W191: indentation contains tabs
        run: flake8 --max-line-length=120 --ignore=W191 ./src/app.py


  editorconfig-checker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Load editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run editorconfig-checker
        run: editorconfig-checker


  markdownlint:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run markdownlint
        uses: articulate/actions-markdownlint@v1


  trivy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ vars.DOCKER_IMAGE_TAG }}
          format: table
          exit-code: 1
          severity: CRITICAL


  gitleaks:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  test:
    needs: build
    runs-on: python-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run tests
        run: python3 -m unittest discover -s ./src/tests -p '*_test.py'


  upload-image:
    needs: [build, flake8, editorconfig-checker, markdownlint, trivy, gitleaks, test]
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-alpine
          push: true
          tags: ${{ vars.DOCKER_IMAGE_TAG }}
