name: CI

on: 
  push:
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME_AND_TAG: ${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}-${{ github.sha }}

jobs:
  call-workflow:
    uses: ivaylopp/mdp-classwork-ci/.github/workflows/ci.yml@main
    permissions:
      packages: write
    secrets: inherit
    with:
      language: java
      java-version: 17
